FROM tiberoofficial/tibero:7.2.4

USER root

RUN yum install -y --setopt=tsflags=nodocs --setopt=install_weak_deps=False \
        libfaketime && \
    yum clean all && \
    rm -rf /var/cache/yum /var/cache/dnf \
           /var/log/yum.log /var/log/dnf.* \
           /usr/share/doc/libfaketime \
           /usr/share/licenses/libfaketime \
           /usr/share/man/man1/faketime.1*

ENV LD_PRELOAD=/usr/lib64/libfaketimeMT.so.1 \
    FAKETIME="-99d" \
    DONT_FAKE_MONOTONIC=1 \
    FAKETIME_NO_CACHE=1
