package com.cmt.e2e.tests.migration.informix;

import java.io.IOException;

import com.cmt.e2e.framework.assertion.DumpGoldenVerifier;
import com.cmt.e2e.framework.assertion.DumpManifest;
import com.cmt.e2e.framework.assertion.MigrationAsserts;
import com.cmt.e2e.framework.command.execution.CommandResult;
import com.cmt.e2e.framework.command.impls.StartCommand;
import com.cmt.e2e.framework.core.CmtTestContext;
import com.cmt.e2e.framework.db.containers.DatabaseContainer;
import com.cmt.e2e.framework.db.containers.InformixContainer;
import com.cmt.e2e.framework.db.init.InformixDatabaseInitializer;
import com.cmt.e2e.framework.junit.TestResources;
import com.cmt.e2e.framework.template.ResolvedScript;
import com.cmt.e2e.framework.template.ScriptTemplateResolver;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * E2E test for IBM Informix 14.10 (e2e seed) -> CMT dump file migration.
 *
 * <p>Source seed lives in {@code src/test/resources/db/informix/} and is
 * documented in {@code docs/seed/informix/SEED_SPEC.md}. Container init
 * provisions {@code e2e_db} and the two OS users; the test then applies
 * the Flyway scenarios as those users.
 *
 * <p><b>Note (golden regeneration required):</b> the golden files under
 * {@code expected/main_user/} reflect CMT 's Informix → CUBRID dump
 * output and must be (re)generated by running
 * {@code RegenerateScripts.INFORMIX_TO_DUMPFILE} once with
 * {@code CMT_E2E_HOLD_OUTPUT=1}, then copying the artifacts from the
 * per-test artifact directory into the resource folder. The manifest
 * below is the best-known shape; any discrepancies surface as
 * {@code DumpGoldenVerifier} failures on the first run.
 */
@Disabled("DEFERRED — see docs/seed/informix/SEED_SPEC.md §0.")
@Testcontainers
@DisplayName("IFX-DO-01: Informix e2e dataset -> dump file migration")
public class InformixToDumpTest {

    // CMT outputs the per-schema directory and file prefix in lowercase
    // ("main_user") even when the source script.xml carries an upper-case
    // schema string. The "INFORMIX" prefix comes from RegenerateScripts '
    // file_prefix=INFORMIX.
    private static final DumpManifest EXPECTED_DUMP = DumpManifest.builder()
        .golden("main_user_clear.sql")
        .golden("main_user_drop_fk.sql")
        .golden("main_user_truncate.sql")
        .golden("INFORMIX_main_user_class")
        .golden("INFORMIX_main_user_fk")
        .golden("INFORMIX_main_user_indexes")
        .golden("INFORMIX_main_user_info")
        .golden("INFORMIX_main_user_pk")
        .golden("INFORMIX_main_user_serial")
        .golden("INFORMIX_main_user_uk")
        .golden("INFORMIX_main_user_updatestatistic")
        .dataFile("INFORMIX_main_user_object")
        .build();

    @RegisterExtension
    final CmtTestContext ctx = new CmtTestContext();

    @Container
    private final DatabaseContainer sourceDb = InformixContainer.withMainUser();

    @Test
    @TestResources("migration/informix/informix_to_dumpfile")
    @DisplayName("generates dump files and reports MIGRATION RESULT: SUCCESS")
    void should_generateDumpFiles_when_sourceIsInformixE2eSeed()
            throws IOException, InterruptedException {
        // Arrange (single-user pattern; cf. SEED_SPEC §1 cross-schema anti-coverage)
        InformixDatabaseInitializer.of((InformixContainer) sourceDb)
            .migrateMain("informix/main_schema");

        ResolvedScript resolved = ScriptTemplateResolver.builder()
            .template(ctx.testPaths().getResourceDir().resolve("script.xml"))
            .source(sourceDb)
            .outputDir(ctx.testPaths().getArtifactDir())
            .scriptFileName("Informix_to_DumpFile.xml")
            .build()
            .resolve();

        // Act
        CommandResult result = ctx.commandRunner().run(
            StartCommand.builder().script(resolved.scriptPath()).build());

        // Assert
        MigrationAsserts.assertMigrationSucceeded(result);
        MigrationAsserts.assertNoFatalStderr(result);
        DumpGoldenVerifier.of(ctx.migrationOutput(resolved.migrationName(), "main_user"))
            .verify(EXPECTED_DUMP, ctx.testPaths().getResourceDir().resolve("expected/main_user"));
    }
}
