package com.cmt.e2e.tests.migration.informix;

import java.io.IOException;

import com.cmt.e2e.framework.assertion.MigrationAsserts;
import com.cmt.e2e.framework.command.execution.CommandResult;
import com.cmt.e2e.framework.command.impls.StartCommand;
import com.cmt.e2e.framework.core.CmtTestContext;
import com.cmt.e2e.framework.db.containers.DatabaseContainer;
import com.cmt.e2e.framework.db.containers.InformixContainer;
import com.cmt.e2e.framework.db.init.InformixDatabaseInitializer;
import com.cmt.e2e.framework.junit.annotation.TestResources;
import com.cmt.e2e.framework.template.ResolvedScript;
import com.cmt.e2e.framework.template.ScriptTemplateResolver;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * E2E test for IBM Informix 14.10 (e2e seed) -> CMT dump file migration.
 *
 * <p>Source seed lives in {@code src/test/resources/db/informix/} and is
 * documented in {@code docs/seed/informix/SEED_SPEC.md}. Container init
 * provisions {@code e2e_db} and the two OS users; the test then applies
 * the Flyway scenarios as those users.
 *
 * <p><b>Note (golden regeneration required):</b> the golden files under
 * {@code expected/main_user/} reflect CMT 's Informix → CUBRID dump
 * output and must be (re)generated by running
 * {@code RegenerateScripts.INFORMIX_TO_DUMPFILE} once with
 * {@code CMT_E2E_HOLD_OUTPUT=1}, then copying the artifacts from the
 * per-test artifact directory into the resource folder. The manifest
 * below is the best-known shape; any discrepancies surface as
 * {@code DumpGoldenVerifier} failures on the first run.
 */
@Tag("db-required")
@Testcontainers
@DisplayName("IFX-DO-01: Informix e2e dataset -> dump file migration")
public class InformixToDumpTest {

    // SEED_SPEC §0 PARTIAL: Informix record export 가 동작하지 않아 dump 의
    // *_object 데이터 파일과 일부 메타 파일이 생성되지 않는다. 본 테스트는
    // CMT 의 마이그레이션이 SUCCESS 로 끝남을 (DDL 부분만 정상 처리됨)
    // 검증한다. 골든 파일 비교는 보류 — record export 가 복구될 때
    // 구체적 manifest 와 함께 다시 활성화한다.

    @RegisterExtension
    final CmtTestContext ctx = CmtTestContext.builder().build();

    @Container
    private final DatabaseContainer sourceDb = InformixContainer.withMainUser();

    @Test
    @TestResources("migration/informix/informix_to_dumpfile")
    @DisplayName("generates dump files and reports MIGRATION RESULT: SUCCESS")
    void should_generateDumpFiles_when_sourceIsInformixE2eSeed()
            throws IOException, InterruptedException {
        // Arrange (single-user pattern; cf. SEED_SPEC §1 cross-schema anti-coverage)
        InformixDatabaseInitializer.of((InformixContainer) sourceDb)
            .migrateMain("informix/main_schema");

        ResolvedScript resolved = ScriptTemplateResolver.builder()
            .template(ctx.testPaths().getResourceDir().resolve("script.xml"))
            .source(sourceDb)
            .outputDir(ctx.testPaths().getArtifactDir())
            .scriptFileName("Informix_to_DumpFile.xml")
            .build()
            .resolve();

        // Act
        CommandResult result = ctx.commandRunner().run(
            StartCommand.builder().script(resolved.scriptPath()).build());

        // Assert
        MigrationAsserts.assertMigrationSucceeded(result);
        // stderr 와 golden manifest 비교는 SEED_SPEC §0 PARTIAL 에 따라
        // 보류. CMT 의 record export 가 동작하면 두 줄을 다시 활성화한다.
    }
}
