package com.cmt.e2e.tests.migration.mysql;

import java.io.IOException;

import com.cmt.e2e.framework.assertion.DumpGoldenVerifier;
import com.cmt.e2e.framework.assertion.DumpManifest;
import com.cmt.e2e.framework.assertion.MigrationAsserts;
import com.cmt.e2e.framework.command.execution.CommandResult;
import com.cmt.e2e.framework.command.impls.StartCommand;
import com.cmt.e2e.framework.core.CmtTestContext;
import com.cmt.e2e.framework.db.containers.DatabaseContainer;
import com.cmt.e2e.framework.db.containers.MySqlContainer;
import com.cmt.e2e.framework.db.init.MysqlDatabaseInitializer;
import com.cmt.e2e.framework.junit.annotation.TestResources;
import com.cmt.e2e.framework.template.ResolvedScript;
import com.cmt.e2e.framework.template.ScriptTemplateResolver;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * E2E test for MySQL 8.0 (single-database e2e seed) -> CMT dump file migration.
 *
 * <p>Source seed lives in {@code src/test/resources/db/mysql/} and is
 * documented in {@code docs/seed/mysql/SEED_SPEC.md}. Container entrypoint
 * runs {@code init/00_prepare_database.sql} as root (creates main_schema
 * database + main_user); the test then applies {@code main_schema/V*.sql}
 * via Flyway as main_user. {@code ref_schema} is intentionally absent
 * (SEED_SPEC §1 anti-coverage).
 *
 * <p><b>Note (golden regeneration required):</b> the golden files under
 * {@code expected/ROOT/} reflect CMT 's MySQL → CUBRID dump output and must be
 * (re)generated by running this test once with {@code CMT_E2E_HOLD_OUTPUT=1},
 * then copying the artifacts from the per-test artifact directory into the
 * resource folder. The manifest below is the best-known shape; any
 * discrepancies surface as DumpGoldenVerifier failures on the first run.
 */
@Tag("db-required")
@Testcontainers
@DisplayName("MYS-DO-01: MySQL e2e dataset -> dump file migration")
public class MysqlToDumpTest {

    // CMT outputs the per-schema directory and file prefix in lowercase (`root`)
    // even when the source script.xml carries `<schema source="ROOT" .../>`.
    // The "MYSQL" prefix comes from RegenerateScripts ' file_prefix=MYSQL.
    //
    // This manifest reflects the file set CMT actually emits for the post-cleanup
    // MySQL seed (no view → no vclass*, no AUTO_INCREMENT → no serial).
    private static final DumpManifest EXPECTED_DUMP = DumpManifest.builder()
        .golden("root_clear.sql")
        .golden("root_drop_fk.sql")
        .golden("root_truncate.sql")
        .golden("MYSQL_root_class")
        .golden("MYSQL_root_fk")
        .golden("MYSQL_root_indexes")
        .golden("MYSQL_root_info")
        .golden("MYSQL_root_pk")
        .golden("MYSQL_root_uk")
        .golden("MYSQL_root_updatestatistic")
        .dataFile("MYSQL_root_object")
        .build();

    @RegisterExtension
    final CmtTestContext ctx = CmtTestContext.builder().build();

    @Container
    private final DatabaseContainer sourceDb = MySqlContainer.withMainUser();

    @Test
    @TestResources("migration/mysql/mysql_to_dumpfile")
    @DisplayName("generates dump files and reports MIGRATION RESULT: SUCCESS")
    void should_generateDumpFiles_when_sourceIsMysqlE2eSeed() throws IOException, InterruptedException {
        // Arrange
        MysqlDatabaseInitializer.of((MySqlContainer) sourceDb).migrateMain("mysql/main_schema");

        ResolvedScript resolved = ScriptTemplateResolver.builder()
            .template(ctx.testPaths().getResourceDir().resolve("script.xml"))
            .source(sourceDb)
            .outputDir(ctx.testPaths().getArtifactDir())
            .scriptFileName("MySQL_to_DumpFile.xml")
            .build()
            .resolve();

        // Act
        CommandResult result = ctx.commandRunner().run(
            StartCommand.builder().script(resolved.scriptPath()).build());

        // Assert
        MigrationAsserts.assertMigrationSucceeded(result);
        MigrationAsserts.assertNoFatalStderr(result);
        DumpGoldenVerifier.of(ctx.migrationOutput(resolved.migrationName(), "root"))
            .verify(EXPECTED_DUMP, ctx.testPaths().getResourceDir().resolve("expected/root"));
    }
}
