package com.cmt.e2e.tests.migration.cubrid;

import java.io.IOException;

import com.cmt.e2e.framework.assertion.DumpGoldenVerifier;
import com.cmt.e2e.framework.assertion.DumpManifest;
import com.cmt.e2e.framework.assertion.MigrationAsserts;
import com.cmt.e2e.framework.command.execution.CommandResult;
import com.cmt.e2e.framework.command.impls.StartCommand;
import com.cmt.e2e.framework.core.CmtTestContext;
import com.cmt.e2e.framework.db.containers.CubridContainer;
import com.cmt.e2e.framework.db.containers.DatabaseContainer;
import com.cmt.e2e.framework.db.init.ClasspathSqlRunner;
import com.cmt.e2e.framework.db.init.DatabaseInitializer;
import com.cmt.e2e.framework.junit.annotation.TestResources;
import com.cmt.e2e.framework.template.ResolvedScript;
import com.cmt.e2e.framework.template.ScriptTemplateResolver;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * E2E test for CUBRID (e2e seed: REF_SCHEMA + MAIN_SCHEMA) -> CMT dump file migration.
 *
 * <p>Source seed lives in {@code src/test/resources/db/cubrid/} and is
 * documented in {@code docs/seed/cubrid/SEED_SPEC.md}. The test bootstraps it
 * before running the dump:
 * <ol>
 *   <li>{@code init/00_prepare_database.sql} as {@code dba} (creates the
 *       {@code MAIN_SCHEMA} and {@code REF_SCHEMA} users).</li>
 *   <li>{@code ref_schema/V*.sql} as {@code REF_SCHEMA}.</li>
 *   <li>{@code main_schema/V*.sql} as {@code MAIN_SCHEMA}.</li>
 * </ol>
 *
 * <p><b>Note (golden regeneration required):</b> the golden files under
 * {@code expected/MAIN_SCHEMA/} reflect the new e2e dataset and must be
 * (re)generated by running this test once with {@code CMT_E2E_HOLD_OUTPUT=1},
 * then copying the artifacts from {@code $CMT_CONSOLE_HOME/output/.../MAIN_SCHEMA/}
 * into the resource directory. The manifest below is the best-known shape;
 * any discrepancies surface as DumpGoldenVerifier failures on the first run.
 */
@Tag("db-required")
@Testcontainers
@DisplayName("CUB-DO-01: CUBRID e2e dataset -> dump file migration")
public class CubridToDumpTest {

    private static final DumpManifest EXPECTED_DUMP = DumpManifest.builder()
        .golden("MAIN_SCHEMA_clear.sql")
        .golden("MAIN_SCHEMA_drop_fk.sql")
        .golden("MAIN_SCHEMA_truncate.sql")
        .golden("demodb_MAIN_SCHEMA_class")
        .golden("demodb_MAIN_SCHEMA_fk")
        .golden("demodb_MAIN_SCHEMA_grant.REF_SCHEMA")
        .golden("demodb_MAIN_SCHEMA_indexes")
        .golden("demodb_MAIN_SCHEMA_info")
        .golden("demodb_MAIN_SCHEMA_pk")
        .golden("demodb_MAIN_SCHEMA_serial")
        .golden("demodb_MAIN_SCHEMA_synonym")
        .golden("demodb_MAIN_SCHEMA_uk")
        .golden("demodb_MAIN_SCHEMA_updatestatistic")
        .golden("demodb_MAIN_SCHEMA_vclass")
        .golden("demodb_MAIN_SCHEMA_vclass_query_spec")
        .dataFile("demodb_MAIN_SCHEMA_object")
        .build();

    @RegisterExtension
    final CmtTestContext ctx = CmtTestContext.builder().build();

    @Container
    private final DatabaseContainer sourceDb = CubridContainer.withEmptyDb();

    @Test
    @TestResources("migration/cubrid/cubrid_to_dumpfile")
    @DisplayName("generates dump files and reports MIGRATION RESULT: SUCCESS")
    void should_generateDumpFiles_when_sourceIsCubridE2eSeed() throws IOException, InterruptedException {
        // Arrange: bootstrap the two-user e2e seed.
        CubridContainer cubrid = (CubridContainer) sourceDb;
        String dbaUrl = cubrid.getJdbcUrl("cubdb", "dba");
        ClasspathSqlRunner.runDirectory(dbaUrl, "dba", "", "db/cubrid/init");
        DatabaseInitializer.of(cubrid, "cubdb", "REF_SCHEMA", "cmt").migrate("cubrid/ref_schema");
        DatabaseInitializer.of(cubrid, "cubdb", "MAIN_SCHEMA", "cmt").migrate("cubrid/main_schema");

        ResolvedScript resolved = ScriptTemplateResolver.builder()
            .template(ctx.testPaths().getResourceDir().resolve("script.xml"))
            .source(sourceDb)
            .outputDir(ctx.testPaths().getArtifactDir())
            .scriptFileName("CUBRID_to_DumpFile.xml")
            .build()
            .resolve();

        // Act
        CommandResult result = ctx.commandRunner().run(
            StartCommand.builder().script(resolved.scriptPath()).build());

        // Assert
        MigrationAsserts.assertMigrationSucceeded(result);
        MigrationAsserts.assertNoFatalStderr(result);
        DumpGoldenVerifier.of(ctx.migrationOutput(resolved.migrationName(), "MAIN_SCHEMA"))
            .verify(EXPECTED_DUMP, ctx.testPaths().getResourceDir().resolve("expected/MAIN_SCHEMA"));
    }
}
