<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cubrid.cubridmigration</groupId>
        <artifactId>product</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../</relativePath>
    </parent>
    <artifactId>com.cubrid.cubridmigration.console</artifactId>
    <packaging>pom</packaging>

    <build>
        <plugins>
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>${maven-antrun-plugin.version}</version>
                <executions>
                    <execution>
                        <id>download-jre</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <get src="${jre.download.url}/OpenJDK21U-jre_x64_windows_hotspot_21.0.7_6.zip" dest="${project.build.directory}/win-jre.zip" />
                                <get src="${jre.download.url}/OpenJDK21U-jre_x64_linux_hotspot_21.0.7_6.tar.gz" dest="${project.build.directory}/linux-jre.tar.gz" />
                                <get src="${jre.download.url}/OpenJDK21U-jre_aarch64_mac_hotspot_21.0.7_6.tar.gz" dest="${project.build.directory}/mac-aarch64-jre.tar.gz" />
                            </target>
                        </configuration>
                    </execution>
                    <execution>
                        <id>unpack-jre</id>
                        <phase>package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <property name="jre.dir" value="${project.build.directory}/jre"/>
                                <unzip src="${project.build.directory}/win-jre.zip" dest="${jre.dir}/win">
                                    <mapper type="regexp" from="^[^/]+/(.*)$" to="win-jre/\1"/>
                                </unzip>
                                <untar src="${project.build.directory}/linux-jre.tar.gz" dest="${jre.dir}/linux" compression="gzip">
                                    <mapper type="regexp" from="^[^/]+/(.*)$" to="linux-jre/\1"/>
                                </untar>
                                <untar src="${project.build.directory}/mac-aarch64-jre.tar.gz" dest="${jre.dir}/mac-aarch64" compression="gzip">
                                    <mapper type="regexp" from="^[^/]+/(.*)$" to="mac-aarch64-jre/\1"/>
                                </untar>
                                <chmod perm="755">
                                    <fileset dir="${jre.dir}/linux/linux-jre/bin" includes="**/*"/>
                                    <fileset dir="${jre.dir}/mac-aarch64/mac-aarch64-jre/Contents/Home/bin" includes="**/*"/>
                                </chmod>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>${maven-assembly-plugin.version}</version>
                <executions>
                    <execution>
                        <id>migrationconsole-tar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>${basedir}/console-tar.xml</descriptor>
                            </descriptors>
                            <finalName>${cubridmigration-console}-${cubridmigration-version}</finalName>
                            <archive>
                                <manifest>
                                    <addClasspath>true</addClasspath>
                                </manifest>
                            </archive>
                        </configuration>
                    </execution>
                    <execution>
                        <id>migrationconsole-zip</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>${basedir}/console-zip.xml</descriptor>
                            </descriptors>
                            <finalName>${cubridmigration-console}-${cubridmigration-version}</finalName>
                            <archive>
                                <manifest>
                                    <addClasspath>true</addClasspath>
                                </manifest>
                            </archive>
                        </configuration>
                    </execution>
                    <execution>
                        <id>migrationconsole-mac-tar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>${basedir}/console-mac-tar.xml</descriptor>
                            </descriptors>
                            <finalName>${cubridmigration-console}-${cubridmigration-version}</finalName>
                            <archive>
                                <manifest>
                                    <addClasspath>true</addClasspath>
                                </manifest>
                            </archive>
                        </configuration>
                    </execution>
                </executions>

                <configuration>
                    <tarLongFileMode>posix</tarLongFileMode>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
    <dependencies>
        <dependency>
            <groupId>com.cubrid.cubridmigration</groupId>
            <artifactId>com.cubrid.cubridmigration.command</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
