package com.cmt.e2e.tests.migration.oracle;

import com.cmt.e2e.framework.assertion.DumpGoldenVerifier;
import com.cmt.e2e.framework.assertion.DumpManifest;
import com.cmt.e2e.framework.assertion.MigrationAsserts;
import com.cmt.e2e.framework.command.execution.CommandResult;
import com.cmt.e2e.framework.command.impls.StartCommand;
import com.cmt.e2e.framework.core.CmtTestContext;
import com.cmt.e2e.framework.db.containers.OracleContainer;
import com.cmt.e2e.framework.db.init.OracleDatabaseInitializer;
import com.cmt.e2e.framework.junit.TestResources;
import com.cmt.e2e.framework.template.ResolvedScript;
import com.cmt.e2e.framework.template.ScriptTemplateResolver;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * E2E test for Oracle 11g (two users, e2e dataset)
 * -> CMT dump file migration.
 *
 * <p>All artifacts listed in {@link #EXPECTED_DUMP} must be generated.
 * If the outputs differ from expectations, detailed diagnostics remain in
 * the per-test log.
 *
 * <p><b>Note (golden regeneration required):</b> the golden files under
 * {@code expected/MAIN_SCHEMA/} reflect the new e2e dataset and must be
 * (re)generated by running this test once after the dataset refresh,
 * then copying the artifacts from {@code target/e2e/.../actual/} into the
 * resource directory. The file list below is the best-known shape based on
 * the new dataset; any discrepancies surface as DumpGoldenVerifier failures
 * on the first run and should be reconciled by updating either the manifest
 * or the golden files (whichever is the truth).
 */
@Testcontainers
@DisplayName("ORA-DO-01: Oracle e2e dataset -> dump file migration")
public class OracleToDumpTest {

    private static final DumpManifest EXPECTED_DUMP = DumpManifest.builder()
        .golden("MAIN_SCHEMA_clear.sql")
        .golden("MAIN_SCHEMA_truncate.sql")
        .golden("MAIN_SCHEMA_drop_fk.sql")
        .golden("XE_MAIN_SCHEMA_class")
        .golden("XE_MAIN_SCHEMA_pk")
        .golden("XE_MAIN_SCHEMA_fk")
        .golden("XE_MAIN_SCHEMA_uk")
        .golden("XE_MAIN_SCHEMA_indexes")
        .golden("XE_MAIN_SCHEMA_serial")
        .golden("XE_MAIN_SCHEMA_info")
        .golden("XE_MAIN_SCHEMA_updatestatistic")
        .golden("XE_MAIN_SCHEMA_vclass")
        .golden("XE_MAIN_SCHEMA_vclass_query_spec")
        .golden("XE_MAIN_SCHEMA_function")
        .golden("XE_MAIN_SCHEMA_function_header")
        .golden("FUNCTION/XE_MAIN_SCHEMA_E2E_CUSTOMER_LABEL_FN_function")
        .golden("XE_MAIN_SCHEMA_procedure")
        .golden("XE_MAIN_SCHEMA_procedure_header")
        .golden("PROCEDURE/XE_MAIN_SCHEMA_E2E_UPSERT_CUSTOMER_PROC_procedure")
        .golden("XE_MAIN_SCHEMA_synonym")
        .golden("XE_MAIN_SCHEMA_grant.REF_SCHEMA")
        .dataDirectory("objects",
            "XE_MAIN_SCHEMA_E2E_BINARY_TYPES",
            "XE_MAIN_SCHEMA_E2E_CUSTOMER",
            "XE_MAIN_SCHEMA_E2E_EMPLOYEE",
            "XE_MAIN_SCHEMA_E2E_NUMERIC_TYPES",
            "XE_MAIN_SCHEMA_E2E_ORACLE_LOCATOR_TYPES",
            "XE_MAIN_SCHEMA_E2E_ORDER",
            "XE_MAIN_SCHEMA_E2E_ORDER_LINE",
            "XE_MAIN_SCHEMA_E2E_TEMPORAL_TYPES",
            "XE_MAIN_SCHEMA_E2E_TEXT_TYPES",
            "XE_MAIN_SCHEMA_flyway_schema_history")
        .build();

    @RegisterExtension
    final CmtTestContext ctx = new CmtTestContext();

    @Container
    private final OracleContainer sourceDb = OracleContainer.withTwoUsers();

    @Test
    @TestResources("migration/oracle/oracle_to_dumpfile")
    @DisplayName("generates dump files and reports MIGRATION RESULT: SUCCESS")
    void should_generateDumpFiles_when_sourceIsOracleOnline() throws Exception {
        // Arrange
        OracleDatabaseInitializer.of(sourceDb)
            .migrateAs(sourceDb.getRefUser(),  sourceDb.getRefPassword(),  "oracle/ref_schema")
            .migrateAs(sourceDb.getMainUser(), sourceDb.getMainPassword(), "oracle/main_schema");

        ResolvedScript resolved = ScriptTemplateResolver.builder()
            .template(ctx.testPaths().getResourceDir().resolve("script.xml"))
            .source(sourceDb)
            .outputDir(ctx.testPaths().getArtifactDir())
            .scriptFileName("Oracle_to_DumpFile.xml")
            .build()
            .resolve();

        // Act
        CommandResult result = ctx.commandRunner().run(
            StartCommand.builder().script(resolved.scriptPath()).build());

        // Assert
        MigrationAsserts.assertMigrationSucceeded(result);
        MigrationAsserts.assertNoFatalStderr(result);
        DumpGoldenVerifier.of(ctx.migrationOutput(resolved.migrationName(), "MAIN_SCHEMA"))
            .verify(EXPECTED_DUMP, ctx.testPaths().getResourceDir().resolve("expected/MAIN_SCHEMA"));
    }
}
