package com.cmt.e2e.tests.migration.mariadb;

import java.io.IOException;

import com.cmt.e2e.framework.assertion.DumpGoldenVerifier;
import com.cmt.e2e.framework.assertion.DumpManifest;
import com.cmt.e2e.framework.assertion.MigrationAsserts;
import com.cmt.e2e.framework.command.CommandResult;
import com.cmt.e2e.framework.command.StartCommand;
import com.cmt.e2e.framework.core.CmtTestContext;
import com.cmt.e2e.framework.db.containers.DatabaseContainer;
import com.cmt.e2e.framework.db.containers.MariaDbContainer;
import com.cmt.e2e.framework.db.init.MariadbDatabaseInitializer;
import com.cmt.e2e.framework.core.TestResources;
import com.cmt.e2e.framework.template.ResolvedScript;
import com.cmt.e2e.framework.template.ScriptTemplateResolver;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * E2E test for MariaDB 11 (single-database e2e seed) -> CMT dump file migration.
 *
 * <p>Source seed lives in {@code src/test/resources/db/mariadb/} and is
 * documented in {@code docs/seed/mariadb/SEED_SPEC.md}. Container entrypoint
 * runs {@code init/00_prepare_database.sql} as root; the test then applies
 * {@code main_schema/V*.sql} via Flyway as main_user.
 *
 * <p><b>Note (golden regeneration required):</b> the goldens under
 * {@code expected/root/} reflect CMT 's MariaDB → CUBRID dump output and
 * must be (re)generated by running this test once with
 * {@code CMT_E2E_HOLD_OUTPUT=1}, then copying the artifacts from the
 * per-test artifact directory into the resource folder. The manifest below
 * mirrors what the first successful run produced (file_prefix=MARIADB,
 * lowercase {@code root} schema folder, plus {@code _vclass*} and
 * {@code _serial} when view / sequence-equivalent objects survive).
 */
@Disabled("DEFERRED — see docs/seed/mariadb/SEED_SPEC.md §0.")
@Testcontainers
@DisplayName("MAR-DO-01: MariaDB e2e dataset -> dump file migration")
public class MariadbToDumpTest {

    // CMT outputs the per-schema folder and file prefix in lowercase (`root`)
    // even when the source script.xml carries `<schema source="ROOT" .../>`.
    // The "MARIADB" prefix comes from RegenerateScripts ' file_prefix=MARIADB.
    //
    // No vclass / vclass_query_spec files because view is anti-coverage
    // (CMT 's view body translation bug — same as MySQL). No serial file
    // because AUTO_INCREMENT is captured as an attribute flag, not a
    // standalone sequence object.
    private static final DumpManifest EXPECTED_DUMP = DumpManifest.builder()
        .golden("root_clear.sql")
        .golden("root_drop_fk.sql")
        .golden("root_truncate.sql")
        .golden("MARIADB_root_class")
        .golden("MARIADB_root_fk")
        .golden("MARIADB_root_indexes")
        .golden("MARIADB_root_info")
        .golden("MARIADB_root_pk")
        .golden("MARIADB_root_uk")
        .golden("MARIADB_root_updatestatistic")
        .dataFile("MARIADB_root_object")
        .build();

    @RegisterExtension
    final CmtTestContext ctx = new CmtTestContext();

    @Container
    private final DatabaseContainer sourceDb = MariaDbContainer.withMainUser();

    @Test
    @TestResources("migration/mariadb/mariadb_to_dumpfile")
    @DisplayName("generates dump files and reports MIGRATION RESULT: SUCCESS")
    void should_generateDumpFiles_when_sourceIsMariadbE2eSeed() throws IOException, InterruptedException {
        // Arrange
        MariadbDatabaseInitializer.of((MariaDbContainer) sourceDb).migrateMain("mariadb/main_schema");

        ResolvedScript resolved = ScriptTemplateResolver.builder()
            .template(ctx.testPaths().getResourceDir().resolve("script.xml"))
            .source(sourceDb)
            .outputDir(ctx.testPaths().getArtifactDir())
            .scriptFileName("MariaDB_to_DumpFile.xml")
            .build()
            .resolve();

        // Act
        CommandResult result = ctx.commandRunner().run(
            StartCommand.builder().script(resolved.scriptPath()).build());

        // Assert
        MigrationAsserts.assertMigrationSucceeded(result);
        MigrationAsserts.assertNoFatalStderr(result);
        DumpGoldenVerifier.of(ctx.migrationOutput(resolved.migrationName(), "root"))
            .verify(EXPECTED_DUMP, ctx.testPaths().getResourceDir().resolve("expected/root"));
    }
}
